package pt.tecnico.grpc.mainServer;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.grpc.UserMainServer;
import pt.tecnico.grpc.UserMainServerServiceGrpc;

import io.grpc.stub.StreamObserver;

public class MainServerServiceImpl extends UserMainServerServiceGrpc.UserMainServerServiceImplBase {

	@Override
	public void greeting(UserMainServer.HelloRequest request, StreamObserver<UserMainServer.HelloResponse> responseObserver) {

		// HelloRequest has auto-generated toString method that shows its contents
		System.out.println(request);

		// You must use a builder to construct a new Protobuffer object
		UserMainServer.HelloResponse response = UserMainServer.HelloResponse.newBuilder()
				.setGreeting("Hello " + request.getName()).build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}

}
